version: '3'

tasks:
  web:
    desc: Run the server
    deps: [tailwind-debug]
    cmds:
      - go run . web

  watch:
    desc: Watch for changed files & restart the server
    watch: true
    # run: when_changed
    sources:
      - '**/*.css'
      - '**/*.go'
      - '**/*.svg'
      - '**/*.templ'
      - '**/*.yml'
    deps: [tailwind-debug, fmt]
    cmds:
      - go run . web

  tailwind-debug:
    desc: Tailwind with human-readable output
    deps: [templ]
    cmds:
      - tailwindcss --content "./web/**/*.templ" --input web/static/src.css --output web/static/gen.css

  tailwind-minify:
    desc: Tailwind minified
    sources:
      - '**/*.templ'
      - web/static/src.css
    cmds:
      - tailwindcss --minify --content "./web/**/*.templ" --input web/static/src.css --output web/static/gen.css
    generates:
      - web/static/gen.css

  templ:
    desc: Re-gen Templ templates
    sources:
      - '**/*.templ'
    cmds:
      - templ generate
      - templ fmt .
    generates:
      - '**/*_templ.go'

  fmt:
    desc: Format all sources
    cmds:
      - go mod tidy
      - gofumpt -l -w .

  update:
    desc: Update dependencies
    deps: [setup.macos, fmt]
    cmds:
      - go get -u ./...

  install:
    desc: Build & install binary
    deps: [tailwind-minify, templ, fmt]
    cmds:
      - go install .

  setup.macos:
    desc: Install tools & dependencies for MacOS
    cmds:
      - brew install go-task/tap/go-task
      - brew install tailwindcss
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install mvdan.cc/gofumpt@latest
